### ISSUE TITLE
"plutoc -p" does not report unknown type hint errors

### ISSUE THREAD

**Issue by Sainan** [PlutoLang/Pluto#137] opened 2022-10-22 21:56 UTC
Example script:
```Lua
local test: deez
```
Trying to run it will show the error, but using `plutoc -p` to lint it does not show the error.

**Comment by well-in-that-case** [comment] 2022-10-23 02:27
When trying to repro this, I would crash on Clang/MinGW. MSVC did not crash. The latest commit on `main` was intended to be more consistent with how type mismatch is handled elsewhere in the parser, but it appears that commit has fixed the crashes and this bug. 

If my observation is correct, then you can close the issue. If that portion of the parser is intended to error for a reason I forgor, lmk.

**Comment by Sainan** [comment] 2022-10-23 02:31
Well, I think the underlying issue that luaK_semerror does not report to `plutoc -p` still exists?

**Comment by well-in-that-case** [comment] 2022-10-23 02:38
`luaK_semerror` is normal syntax error that invalidates the token to prevent `near <token>` being appended to error messages. It's working fine everywhere else. Any sort of error was causing UB in this area, so that might've been why it wasn't reporting on MSVC, then crashing on other compilers.

I don't know why UB was invoked, but the effects of it are gone now.

**Comment by Sainan** [comment] 2022-10-23 02:42
Hmm, I can see that the unknown attribute error does not have this problem. Maybe it's related to calling luaX_prev before? Tho that error would also benefit from that since the following code
```Lua
local test <deez
>
```
causes the error reported to be on line 2.

**Comment by well-in-that-case** [comment] 2022-10-23 02:44
I did my testing with Clang/MinGW on the 0.5.0 branch, where the `luaX_prev` fix wasn't present. The problematic line was zeroed-out to be luaK_semerror.

**Comment by Sainan** [comment] 2022-10-23 02:46
Yeah, this also doesn't seem to be causing issues:
![image](https://user-images.githubusercontent.com/63328889/197370666-9d43f4e8-27da-4f39-a7d3-6f9bd461c77e.png)

It's weird, but fixed now, I guess.

**Closed as completed** 2022-10-23 02:46 UTC
Labels: bug
